apiVersion: apps/v1
kind: Deployment
metadata:
  name: payroll-website
  labels:
    app: payroll-website
spec:
  replicas: 5
  selector:
    matchLabels:
      app: payroll-website
  template:
    metadata:
      labels:
        app: payroll-website
    spec:
      containers:
      - name: payroll-website
        image: staffengineering/payroll_website:v1
        ports:
        - containerPort: 5170

---
apiVersion: v1
kind: Service
metadata:
  name: payroll-website-service
spec:
  selector:
    app: payroll-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5170
  type: ClusterIP
