apiVersion: apps/v1
kind: Deployment
metadata:
  name: koya-api
  labels:
    app: koya-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koya-api
  template:
    metadata:
      labels:
        app: koya-api
    spec:
      containers:
        - name: koya-api
          image: staffengineering/koya-api:v1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: koya-api-secrets
                  key: DATABASE_URL
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: koya-api-secrets
                  key: KEYCLOAK_CLIENT_SECRET
            - name: KEYCLOAK_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: koya-api-secrets
                  key: KEYCLOAK_ADMIN_USERNAME
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: koya-api-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KEYCLOAK_SERVER_URL
              value: "http://161.97.73.139:8089"
            - name: KEYCLOAK_REALM
              value: "learnfinity-test"
            - name: KEYCLOAK_CLIENT_ID
              value: "learnfinity-api"
            - name: KEYCLOAK_ENABLED
              value: "true"
            - name: AUTH_STRATEGY
              value: "keycloak"
            - name: ALLOW_INTERNAL_AUTH
              value: "false"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: koya-api-service
spec:
  selector:
    app: koya-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
