# Deployment-payroll-website
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payroll-website
  namespace: default
  labels:
    app: payroll-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payroll-website
  template:
    metadata:
      labels:
        app: payroll-website
    spec:
      containers:
      - name: payroll-website
        image: staffengineering/payroll_website:v1
        ports:
        - containerPort: 5170
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
# Service-payroll-website
apiVersion: v1
kind: Service
metadata:
  name: payroll-website-service
  namespace: default
spec:
  selector:
    app: payroll-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5170
  type: ClusterIP